
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jenaaplication.RDFManager;
import jenaaplication.TwitterWrapper;
import org.apache.jena.atlas.logging.LogCtl;
import org.apache.jena.iri.impl.Main;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.riot.RDFDataMgr;
import org.apache.jena.riot.RDFFormat;
import twitter4j.Status;
import twitter4j.TwitterException;


public class MainFrame extends javax.swing.JFrame {
    
    String ruta = "./";
    public MainFrame() {
        LogCtl.setCmdLogging();
        initComponents();
        this.setTitle("Busca Tweets");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoFormato = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        searchStringField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        RDFXMLRadio = new javax.swing.JRadioButton();
        turtleRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tamField = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        themeField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        ayudaMenu = new javax.swing.JMenu();
        usoSubMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cantidad de muestras");

        searchStringField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchStringFieldKeyPressed(evt);
            }
        });

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        grupoFormato.add(RDFXMLRadio);
        RDFXMLRadio.setText("RDF/XML ");
        RDFXMLRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDFXMLRadioActionPerformed(evt);
            }
        });

        grupoFormato.add(turtleRadio);
        turtleRadio.setSelected(true);
        turtleRadio.setText("Turtle");
        turtleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turtleRadioActionPerformed(evt);
            }
        });

        jLabel2.setText("Formato de salida");

        tamField.setModel(new javax.swing.SpinnerNumberModel(10, 1, 200, 1));
        tamField.setToolTipText("introduza un numero entre 1 y 200");
        tamField.setName("tamField"); // NOI18N

        jLabel3.setText("Patron");

        jLabel4.setText("Tema");

        ayudaMenu.setText("Ayuda");

        usoSubMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        usoSubMenu.setText("Uso");
        usoSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usoSubMenuActionPerformed(evt);
            }
        });
        ayudaMenu.add(usoSubMenu);

        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchStringField)
                            .addComponent(themeField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tamField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(searchButton))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RDFXMLRadio)
                    .addComponent(turtleRadio)
                    .addComponent(jLabel2))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(searchStringField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(themeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turtleRadio))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RDFXMLRadio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchStringFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchStringFieldKeyPressed

    }//GEN-LAST:event_searchStringFieldKeyPressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (!fieldsAreEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos de tema y Patron deben de estar rellenos", "Adverterncia", JOptionPane.WARNING_MESSAGE);
            return ;
        }
        
        List<Status> tweets;
        
        String resultado="";
        try{
            tweets = TwitterWrapper.searchTweets(searchStringField.getText(),(Integer)tamField.getValue());
            RDFManager manager = new RDFManager(searchStringField.getText(), themeField.getText() );
            for (Status tweet: tweets){
                manager.createGraph(tweet);
            }

            save(manager);
            
        }catch(TwitterException e){
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed
    
    private boolean fieldsAreEmpty(){
        return searchStringField.getText().trim().length() > 0 && 
               themeField.getText().trim().length() > 0;
    }
    
    private void save(RDFManager manager){
        Model model = manager.getModel();
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(this);
        if(result == JFileChooser.CANCEL_OPTION)return;
        if(result == JFileChooser.APPROVE_OPTION);
        String name = fileChooser.getSelectedFile().getAbsolutePath();
        try{
            FileWriter writer;
            if (turtleRadio.isSelected()){
                writer = new FileWriter(name + ".ttl");
                RDFDataMgr.write(writer, model, RDFFormat.TURTLE);
                writer.close();
            }else if (RDFXMLRadio.isSelected()){
                writer = new FileWriter(name + ".rdf");
                RDFDataMgr.write(writer, model, RDFFormat.RDFXML);
                writer.close();
            }
        }catch(Exception e){
        }
    }
    
    private void RDFXMLRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDFXMLRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDFXMLRadioActionPerformed

    private void usoSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usoSubMenuActionPerformed
        
        String mensaje = "Debe introducir un termino de busqueda y un numero de resultados(por defecto 10 y máximo 200)\n"
                + "Una vez busquemos el termino se abrirá una ventana para que podamos seleccionar la ruta donde\n"
                + "queremos guardar el archivo, se guardará con la extension \".txt\"";
        JOptionPane.showMessageDialog(this, mensaje, "Informacion", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_usoSubMenuActionPerformed

    private void turtleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turtleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turtleRadioActionPerformed

    
    public void save(File file,String res){
        try{
           FileWriter writer = new FileWriter(file + ".txt");
           writer.write(res);
           writer.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RDFXMLRadio;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.ButtonGroup grupoFormato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchStringField;
    private javax.swing.JSpinner tamField;
    private javax.swing.JTextField themeField;
    private javax.swing.JRadioButton turtleRadio;
    private javax.swing.JMenuItem usoSubMenu;
    // End of variables declaration//GEN-END:variables
}
